# Data Cleaning

In [73]:
import pandas as pd
import os
import warnings

warnings.filterwarnings("ignore")

In [74]:
# Load dataframes

accident_df = pd.read_csv("../data/raw/accident.csv")
person_df = pd.read_csv("../data/raw/person.csv")
vehicle_df = pd.read_csv("../data/raw/vehicle.csv")

In [75]:
print("Original dataset sizes")
print(f"Accidents: {len(accident_df)}")
print(f"Persons: {len(person_df)}")
print(f"Vehicles: {len(vehicle_df)}")

Original dataset sizes
Accidents: 50103
Persons: 122388
Vehicles: 87461

In [76]:
accident_df.head()

,CASENUM,PSU,PSU_VAR,PSUSTRAT,REGION,REGIONNAME,URBANICITY,URBANICITYNAME,STRATUM,STRATUMNAME,...,MAXSEV_IM,MAXSEV_IMNAME,NUM_INJ,NUM_INJNAME,NO_INJ_IM,NO_INJ_IMNAME,ALCOHOL,ALCOHOLNAME,ALCHL_IM,ALCHL_IMNAME
0,202304632910,39,39,7,2,"Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...",1,Urban Area,10,Stratum 10 - Other,...,0,No Apparent Injury (O),99,All Persons in Crash are Unknown If Injured,0,No Person Injured/Property Damage Only Crash,9,Reported as Unknown,2,No Alcohol Involved
1,202304632916,77,77,9,2,"Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...",2,Rural Area,10,Stratum 10 - Other,...,0,No Apparent Injury (O),99,All Persons in Crash are Unknown If Injured,0,No Person Injured/Property Damage Only Crash,9,Reported as Unknown,2,No Alcohol Involved
2,202304635310,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,Urban Area,10,Stratum 10 - Other,...,0,No Apparent Injury (O),0,No Person Injured/Property Damage Only Crash,0,No Person Injured/Property Damage Only Crash,2,No Alcohol Involved,2,No Alcohol Involved
3,202304635315,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,Urban Area,3,Stratum 3 - Motorcycle Any Injury,...,1,Possible Injury (C),1,1,1,1,2,No Alcohol Involved,2,No Alcohol Involved
4,202304635387,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,Urban Area,8,Stratum 8 - NLMY PV Minor Injury,...,1,Possible Injury (C),1,1,1,1,9,Reported as Unknown,2,No Alcohol Involved

In [77]:
person_df.head()

,CASENUM,VE_FORMS,VEH_NO,PER_NO,PSU,PSU_VAR,PSUSTRAT,REGION,REGIONNAME,URBANICITY,...,ATST_TYPNAME,ALC_RES,ALC_RESNAME,DRUGS,DRUGSNAME,HOSPITAL,HOSPITALNAME,STR_VEH,LOCATION,LOCATIONNAME
0,202304632910,1,1,1,39,39,7,2,"Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...",1,...,Test Not Given,996,Test Not Given,8,Not Reported,0,Not Transported for Treatment,0,0,Occupant of a Motor Vehicle
1,202304632916,1,2,1,77,77,9,2,"Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...",2,...,Test Not Given,996,Test Not Given,8,Not Reported,0,Not Transported for Treatment,0,0,Occupant of a Motor Vehicle
2,202304635310,2,1,1,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,...,Test Not Given,996,Test Not Given,0,No (drugs not involved),0,Not Transported for Treatment,0,0,Occupant of a Motor Vehicle
3,202304635310,2,2,1,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,...,Test Not Given,996,Test Not Given,0,No (drugs not involved),0,Not Transported for Treatment,0,0,Occupant of a Motor Vehicle
4,202304635310,2,2,2,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,...,Test Not Given,996,Test Not Given,8,Not Reported,0,Not Transported for Treatment,0,0,Occupant of a Motor Vehicle

In [78]:
vehicle_df.head()

,CASENUM,VEH_NO,PSU,PSU_VAR,PSUSTRAT,REGION,REGIONNAME,URBANICITY,URBANICITYNAME,STRATUM,...,P_CRASH3,P_CRASH3NAME,PCRASH4,PCRASH4NAME,PCRASH5,PCRASH5NAME,ACC_TYPE,ACC_TYPENAME,ACC_CONFIG,ACC_CONFIGNAME
0,202304632910,1,39,39,7,2,"Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...",1,Urban Area,10,...,99,Unknown/Not Reported,1,Tracking,4,Departed roadway,99,M99-Unknown,999,Unknown Crash Type
1,202304632916,2,77,77,9,2,"Midwest (OH, IN, IL, MI, WI, MN, ND, SD, NE, I...",2,Rural Area,10,...,99,Unknown/Not Reported,1,Tracking,4,Departed roadway,11,C11-Single Driver-Forward Impact-Parked Veh.,103,Single Driver-Struck Object While Moving Forward
2,202304635310,1,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,Urban Area,10,...,99,Unknown/Not Reported,1,Tracking,1,Stayed in original travel lane,87,L87-Intersecting Paths-Straight Paths-Struck o...,502,"Intersecting Paths-Straight Paths, Struck on t..."
3,202304635310,2,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,Urban Area,10,...,99,Unknown/Not Reported,1,Tracking,1,Stayed in original travel lane,86,L86-Intersecting Paths-Straight Paths-Striking...,501,"Intersecting Paths-Straight Paths, Striking fr..."
4,202304635315,1,48,48,12,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",1,Urban Area,3,...,1,No Avoidance Maneuver,1,Tracking,1,Stayed in original travel lane,24,"D24-Same Trafficway, Same Direction-Rear End-S...",202,"Same Trafficway, Same Direction-Rear End, Lead..."

## Normalizing Datasets

In [79]:
before = len(person_df)

# keep only records where airbag status is known (deployed or not deployed)
# remove: 97 (Not Applicable - Not in motor vehicle), 98 (Not Reported), 99 (Unknown)
person_clean = person_df[person_df['AIR_BAG'] < 97].copy()

print(f"Removed {before - len(person_clean)} rows")

Removed 14306 rows

In [80]:
before = len(person_df)

# remove unknown ages
person_clean = person_clean[person_clean['AGE'] < 998]

print(f"Removed {before - len(person_clean)} rows")

Removed 16309 rows

In [81]:
before = len(person_df)

# remove unknown injury severity statuses
person_clean = person_clean[person_clean['INJ_SEV'] != 9]

print(f"Removed {before - len(person_clean)} rows")

Removed 16596 rows

In [82]:
# update airbag deployment to binary
# 20 = Not Deployed, 2-9 = Various deployment types
person_clean['AIR_BAG_DEPLOYED'] = person_clean['AIR_BAG'].apply(lambda x: 0 if x == 20 else 1)

In [83]:
# condense rows to one per vehicle since there may be multiple people per vehicle
# aggregates data from each person in the vehicle into a single row

vehicle_person_agg = person_clean.groupby(['CASENUM', 'VEH_NO']).agg({
    'AIR_BAG_DEPLOYED': ['sum', 'count', 'mean'],  # sum=total deployed, count=total occupants
    'AGE': 'mean',  # average age of occupants
    'SEX': lambda x: x.mode()[0] if len(x.mode()) > 0 else x.iloc[0],  # most common sex
    'INJ_SEV': 'max',  # maximum injury severity in vehicle
    'DRINKING': 'max',  # any drinking in vehicle
    'ALC_STATUS': 'max',  # any positive alcohol status
    'SEAT_POS': 'min',  # minimum seat position 
    'REST_USE': lambda x: (x == 7).any().astype(int),  # 1 if any occupant not restrained (seatbelt)
    'EJECTION': 'max',  # maximum ejection severity
}).reset_index()

In [84]:
# rename columns for easier use
vehicle_person_agg.columns = ['CASENUM', 'VEH_NO', 'AIRBAGS_DEPLOYED_COUNT', 'TOTAL_OCCUPANTS', 
                               'DEPLOYMENT_RATE', 'AVG_AGE', 'PREDOMINANT_SEX', 
                               'MAX_INJURY_SEV', 'ANY_DRINKING', 'ANY_ALCOHOL',
                               'FRONT_MOST_SEAT_POS', 'ANY_UNRESTRAINED', 'MAX_EJECTION']

In [85]:
# define target variable as all airbags deployed = success
vehicle_person_agg['ALL_AIRBAGS_DEPLOYED'] = (
    vehicle_person_agg['AIRBAGS_DEPLOYED_COUNT'] == vehicle_person_agg['TOTAL_OCCUPANTS']
).astype(int)

## Merging Datasets

In [ ]:
accident_features = [
    'CASENUM',
    'REGIONNAME',
    'URBANICITYNAME',  
    'MONTH',
    'MONTHNAME',
    'DAY_WEEK',
    'DAY_WEEKNAME',
    'YEAR',
    'HOUR',
    'HOURNAME',
    'MINUTE',
    'MINUTENAME',
    'HARM_EV',
    'HARM_EVNAME',
    'MAN_COLL',
    'MAN_COLLNAME',
    'TYP_INT',
    'TYP_INTNAME',      
    'REL_ROAD',
    'REL_ROADNAME',
    'WEATHER',
    'WEATHERNAME',
    'LGT_COND',
    'LGT_CONDNAME',
    'NUM_INJ'
]

vehicle_features = [
    'CASENUM',
    'VEH_NO',
    'MAKE',
    'MAKENAME',
    'MOD_YEAR',  
    'MODEL',
    'VPICMODELNAME',
    'BODY_TYP',
    'BODY_TYPNAME',
    'VPICBODYCLASS',
    'VPICBODYCLASSNAME',
    'IMPACT1',
    'IMPACT1NAME',
    'P_CRASH1',
    'P_CRASH1NAME',
    'ACC_CONFIG',
    'ACC_CONFIGNAME',
    'VSPD_LIM',
    'TRAV_SP',
    'ROLLOVER',
    'ROLLOVERNAME',
    'NUMOCCS',
    'VSURCOND',
    'VSURCONDNAME',
    'VEH_ALCH',
    'VEH_ALCHNAME'
]

accident_features_df = accident_df[accident_features].copy()
vehicle_features_df = vehicle_df[vehicle_features].copy()

In [87]:
merged_df = vehicle_features_df.merge(vehicle_person_agg, on=['CASENUM', 'VEH_NO'], how='inner').merge(accident_features_df, on='CASENUM', how='left')
print(f"After merging datasets: {len(merged_df)} rows")

After merging datasets: 79456 rows

In [88]:
merged_df.head()

,CASENUM,VEH_NO,MAKE,MAKENAME,MOD_YEAR,MODEL,BODY_TYP,BODY_TYPNAME,VPICBODYCLASS,VPICBODYCLASSNAME,...,MAN_COLLNAME,TYP_INT,TYP_INTNAME,REL_ROAD,REL_ROADNAME,WEATHER,WEATHERNAME,LGT_COND,LGT_CONDNAME,NUM_INJ
0,202304635310,1,12,Ford,2002,473,34,Light Pickup,60,Pickup,...,Angle,2,Four-Way Intersection,1,On Roadway,1,Clear,1,Daylight,0
1,202304635310,2,63,KIA,2011,402,14,"Compact Utility (Utility Vehicle Categories ""S...",7,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,...,Angle,2,Four-Way Intersection,1,On Roadway,1,Clear,1,Daylight,0
2,202304635315,1,12,Ford,2009,25,6,Station Wagon (excluding van and truck based),7,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,...,Front-to-Rear,1,Not an Intersection,1,On Roadway,1,Clear,3,Dark - Lighted,1
3,202304635315,2,53,Suzuki,2008,705,80,Two Wheel Motorcycle (excluding motor scooters),98,Motorcycle - Street,...,Front-to-Rear,1,Not an Intersection,1,On Roadway,1,Clear,3,Dark - Lighted,1
4,202304635387,1,37,Honda,2011,32,2,"2-door sedan,hardtop,coupe",3,Coupe,...,Front-to-Rear,3,T-Intersection,1,On Roadway,1,Clear,2,Dark - Not Lighted,1

In [89]:
print(f"There are {merged_df.shape[1]} features.")
print(f"Features: {merged_df.columns.to_list()}")

There are 61 features.
Features: ['CASENUM', 'VEH_NO', 'MAKE', 'MAKENAME', 'MOD_YEAR', 'MODEL', 'BODY_TYP', 'BODY_TYPNAME', 'VPICBODYCLASS', 'VPICBODYCLASSNAME', 'IMPACT1', 'IMPACT1NAME', 'P_CRASH1', 'P_CRASH1NAME', 'ACC_CONFIG', 'ACC_CONFIGNAME', 'VSPD_LIM', 'TRAV_SP', 'ROLLOVER', 'ROLLOVERNAME', 'NUMOCCS', 'VSURCOND', 'VSURCONDNAME', 'VEH_ALCH', 'VEH_ALCHNAME', 'AIRBAGS_DEPLOYED_COUNT', 'TOTAL_OCCUPANTS', 'DEPLOYMENT_RATE', 'AVG_AGE', 'PREDOMINANT_SEX', 'MAX_INJURY_SEV', 'ANY_DRINKING', 'ANY_ALCOHOL', 'FRONT_MOST_SEAT_POS', 'ANY_UNRESTRAINED', 'MAX_EJECTION', 'ALL_AIRBAGS_DEPLOYED', 'REGIONNAME', 'URBANICITYNAME', 'MONTH', 'MONTHNAME', 'DAY_WEEK', 'DAY_WEEKNAME', 'YEAR', 'HOUR', 'HOURNAME', 'MINUTE', 'MINUTENAME', 'HARM_EV', 'HARM_EVNAME', 'MAN_COLL', 'MAN_COLLNAME', 'TYP_INT', 'TYP_INTNAME', 'REL_ROAD', 'REL_ROADNAME', 'WEATHER', 'WEATHERNAME', 'LGT_COND', 'LGT_CONDNAME', 'NUM_INJ']

## Filtering Columns

In [90]:
# remove motorcyles from dataframe

clean_df  = merged_df[merged_df['VPICBODYCLASS'] != 12].copy()
print(f"Removed {len(merged_df) - len(clean_df)} rows")

Removed 202 rows

## Explicit Missing Values

In [91]:
na_values = clean_df.isna().sum()
print(na_values[na_values > 0])

Series([], dtype: int64)

In [92]:
# remove explicit missing values
before = len(clean_df)

clean_df = clean_df.dropna()
print(f"Removed {before - len(clean_df)} rows")

Removed 0 rows

## Implicit Missing Values

In [93]:
# only remove implicit missing values for useful features to minimize rows cleaned
before = len(clean_df)

# remove: 998 (Not Reported), 999 (Reported as Unknown)
clean_df = clean_df[clean_df['TRAV_SP'] < 998]
print(f"Removed {before - len(clean_df)} rows")

Removed 41241 rows

In [94]:
before = len(clean_df)

clean_df = clean_df[clean_df['MAKENAME'] != "Not Reported"]
print(f"Removed {before - len(clean_df)} rows")

Removed 3 rows

In [95]:
before = len(clean_df)

clean_df = clean_df[clean_df['VPICBODYCLASS'] < 998]
print(f"Removed {before - len(clean_df)} rows")

Removed 1214 rows

In [96]:
before = len(clean_df)

clean_df = clean_df[clean_df['IMPACT1'] < 98]
print(f"Removed {before - len(clean_df)} rows")

Removed 329 rows

In [97]:
before = len(clean_df)

clean_df = clean_df[clean_df['MOD_YEAR'] < 9998]
print(f"Removed {before - len(clean_df)} rows")

Removed 65 rows

## Feature Engineering

In [98]:
# calculate vehicle age from time of accident
clean_df['VEHICLE_AGE'] = clean_df['YEAR'] - clean_df['MOD_YEAR']

In [99]:
# identify if the accident was head on (frontal) by airbag deployment area
clean_df['FRONTAL_IMPACT'] = clean_df['IMPACT1'].isin(range(1, 13)).astype(int)

In [100]:
# classify accidents into high speed crashes (generally accepted as over 30 mph)
clean_df['HIGH_SPEED_CRASH'] = (clean_df['TRAV_SP'] > 30).astype(int)

# modern airbags typically deploy at around 15-20 mph
# airbags deployment are based on deceleration, but generally this is the minimum range
clean_df['MIN_AIRBAG_SPEED'] = (clean_df['TRAV_SP'] > 20).astype(int)

In [101]:
SEVERE_COLLISION_CODES = {
    # High-energy collisions with motor vehicles
    12,  # Collision with motor vehicle in transport
    54, 55,  # Other motor vehicle collisions
    
    # Fixed object collisions; walls, buildings, barriers
    17, 19, 20, 21, 23, 24, 25, 26,
    
    # Posts, poles, supports, trees, traffic control devices
    30, 31, 32, 33, 34, 35, 38, 39, 40, 41, 42, 43,
    
    # Other fixed objects
    46, 48, 50, 53, 57, 58, 59,
}

In [ ]:
#  create a composite score for the severity of a crash on a scale from 0-100
def calculate_crash_severity(row):
    score = 0
    
    # speed factor
    speed = float(row['TRAV_SP'])
    # exponential scaling for higher speeds
    if speed <= 15:
        score += speed * 0.5  # 0-7.5 points
    elif speed <= 30:
        score += 7.5 + (speed - 15) * 0.8  # 7.5-19.5 points
    elif speed <= 50:
        score += 19.5 + (speed - 30) * 1.0  # 19.5-39.5 points
    else:
        score += 39.5 + min(0.5, (speed - 50) * 0.02)  # 39.5-40 points
    
    # impact location 
    impact_code = int(row['IMPACT1'])
    
    # Categorize impact severity
    if 1 <= impact_code <= 12:  # Clock points (1-12)
        if impact_code in [12, 1, 11, 2, 10]:   # Front impacts are more severe (12, 1, 11 o'clock)
            score += 25  # Frontal/front-corner
        elif impact_code in [3, 4, 8, 9]:
            score += 20  # Side
        else:  
            score += 10  # Rear/side-rear
    elif impact_code in [13, 14]:  # Top/bottom
        score += 30  # Rollover/vertical impact 
    elif impact_code in [61, 62, 63, 81, 82, 83]:  # Left/Right (general)
        score += 15
    else: 
        score += 5 # non collision / unknown

    # type of collision
    harm_ev = int(row['HARM_EV'])
    
    if harm_ev in range(1,5):
        score += 20 # severe: rollover, fire, etc
    elif harm_ev in SEVERE_COLLISION_CODES:
        score += 15 # other vehicles or fixed objects
    else:
        score += 10 # non-fixed objects
    
    # rollovers
    if row['ROLLOVER'] == 3:
        score += 10  # Rollovers are more dangerous
    
    # scale to 0-100
    final_score = min(100, max(0, score))
    
    return final_score

clean_df['CRASH_SEVERITY_SCORE'] = clean_df.apply(calculate_crash_severity, axis=1)

## Final Dataset

In [103]:
print(f"Removed {len(merged_df) - len(clean_df)} total rows")
print(f"Final cleaned dataset shape: {clean_df.shape}")
print(f"Number of features: {clean_df.shape[1]}")

Removed 43054 total rows
Final cleaned dataset shape: (36402, 66)
Number of features: 66

In [104]:
clean_df.head()

,CASENUM,VEH_NO,MAKE,MAKENAME,MOD_YEAR,MODEL,BODY_TYP,BODY_TYPNAME,VPICBODYCLASS,VPICBODYCLASSNAME,...,WEATHER,WEATHERNAME,LGT_COND,LGT_CONDNAME,NUM_INJ,VEHICLE_AGE,FRONTAL_IMPACT,HIGH_SPEED_CRASH,MIN_AIRBAG_SPEED,CRASH_SEVERITY_SCORE
0,202304635310,1,12,Ford,2002,473,34,Light Pickup,60,Pickup,...,1,Clear,1,Daylight,0,21,1,0,0,27.5
1,202304635310,2,63,KIA,2011,402,14,"Compact Utility (Utility Vehicle Categories ""S...",7,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,...,1,Clear,1,Daylight,0,12,1,0,1,55.5
2,202304635315,1,12,Ford,2009,25,6,Station Wagon (excluding van and truck based),7,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,...,1,Clear,3,Dark - Lighted,1,14,1,1,1,69.5
3,202304635315,2,53,Suzuki,2008,705,80,Two Wheel Motorcycle (excluding motor scooters),98,Motorcycle - Street,...,1,Clear,3,Dark - Lighted,1,15,1,0,1,40.5
5,202304635387,2,20,Chevrolet,2018,404,14,"Compact Utility (Utility Vehicle Categories ""S...",7,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,...,1,Clear,2,Dark - Not Lighted,1,5,1,0,0,25.0

In [105]:
# Create new csv file 
folder_name = "../data/interim/"
file_name = "clean_data.csv"
file_path = os.path.join(folder_name, file_name)

clean_df.to_csv(file_path, index=False)